site_name: 我的文档
site_url: https://wubzbz.github.io/playful-csharp-tutorial

theme:
  name: material
  features:
    - navigation.indexes
    - navigation.path
    - navigation.prune
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
    - content.code.select

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: 切换到深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: 切换到浅色模式

  font:
    text: Noto Sans SC
    code: JetBrains Mono

# 插件：自动章节导航
plugins:
  - awesome-pages:
      collapse_single_pages: true
  - search

markdown_extensions:
  - admonition                 # 卡片 !!! ???
  - pymdownx.blocks.tab        # 切换 ///
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.keys              # 按键++
  - pymdownx.mark              # 高亮==
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      toc_depth: 3
 

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
